name: Build and deploy

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:

env:
  DOCKER_IMAGE_NAME: ${{ github.event.repository.name || github.repository }}
  DOCKER_IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # required by gcp auth
    steps:
      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '~> 524.0.0'

      - run: |
          gcloud --version
          gcloud auth list

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: 'pip'

      - run: |
          python -m pip install --upgrade pip
          python -c "import sys; print(sys.version)"
          pip install pytest black
          black --check .
          pip install -r requirements.txt
          pytest

      - run: gcloud auth configure-docker us-docker.pkg.dev
      - uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # see https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            gcr.io/invader-spotter-news-dev/${{ env.DOCKER_IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          # tags:
          #   - ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          #   - latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optimisation pour le cache (optionnel) :
          cache-from: type=gha
          cache-to: type=gha,mode=max
